export const BLOG_POSTS = [
  {
    slug: 'quest-ce-que-le-magnetisme',
    title: "Qu'est-ce que le magnétisme ?",
    excerpt: "Une approche ancestrale de bien-être, transmise par le toucher subtil et la présence.",
    date: '2025-05-14',
    readTime: 6,
    tag: 'Fondamentaux',
    body: [
      "Le magnétisme est une pratique très ancienne qui accompagne l'être humain depuis des siècles. Sans promesse de guérison, il propose un espace de détente, un moment où le corps et l'esprit peuvent relâcher les tensions accumulées.",
      "Le magnétiseur utilise ses mains, sa présence et son intention pour accompagner la personne dans un travail subtil, respectueux de son rythme.",
      "Il ne s'agit ni d'une médecine ni d'un traitement. Le magnétisme se pense comme une approche complémentaire, qui vient soutenir un chemin de mieux-être global.",
    ],
  },
  {
    slug: 'comment-se-deroule-une-seance',
    title: 'Comment se déroule une séance ?',
    excerpt: "De l'accueil au silence, chaque temps de la séance a son rôle. Voici ce que vous vivrez.",
    date: '2025-05-22',
    readTime: 5,
    tag: 'Pratique',
    body: [
      "Une séance dure environ 60 minutes. Elle commence par un temps d'échange, où vous partagez ce qui vous amène et ce que vous ressentez.",
      "Vient ensuite la séance elle-même : nettoyage énergétique, ancrage, libération, recharge, harmonisation et magnétisme ciblé.",
      "Enfin, un temps de retour permet de partager vos ressentis et d'échanger des conseils pour prolonger les bienfaits de la séance dans les jours qui suivent.",
    ],
  },
  {
    slug: 'magnetiseur-geneve-comment-choisir',
    title: 'Magnétiseur à Genève : comment choisir ?',
    excerpt: "Quelques repères simples pour trouver un praticien sérieux, respectueux et à votre écoute.",
    date: '2025-06-02',
    readTime: 7,
    tag: 'Conseils',
    body: [
      "Choisir un magnétiseur à Genève, c'est avant tout choisir une personne. Prenez le temps de lire son parcours, ses valeurs et sa façon de communiquer.",
      "Un praticien sérieux n'emploie jamais un vocabulaire de guérison. Il parle d'accompagnement, de soutien, de mieux-être.",
      "Fiez-vous également à votre ressenti lors du premier échange téléphonique : êtes-vous écouté, respecté, non brusqué ? C'est un excellent indicateur.",
    ],
  },
  {
    slug: 'soins-energetiques-expliques-simplement',
    title: 'Les soins énergétiques expliqués simplement.',
    excerpt: "Une lecture accessible pour démystifier ce que sont, et ne sont pas, les soins énergétiques.",
    date: '2025-06-10',
    readTime: 6,
    tag: 'Vulgarisation',
    body: [
      "Les soins énergétiques regroupent différentes approches (magnétisme, Reiki, harmonisation) qui ont un point commun : elles proposent un espace d'apaisement et de présence.",
      "Ces approches ne remplacent aucun traitement médical. Elles s'inscrivent dans une démarche de bien-être complémentaire, en dialogue avec le corps médical si besoin.",
      "Ce que la personne reçoit varie selon les sensibilités : détente profonde, lâcher-prise, clarté, apaisement. Chaque personne vit sa séance à sa façon.",
    ],
  },
  {
    slug: 'stress-et-energie-quel-lien',
    title: 'Stress et énergie : quel lien ?',
    excerpt: "Comprendre comment le stress altère le corps et pourquoi un accompagnement doux peut aider.",
    date: '2025-06-18',
    readTime: 5,
    tag: 'Bien-être',
    body: [
      "Le stress chronique laisse des empreintes dans le corps : sommeil perturbé, tensions musculaires, fatigue installe.",
      "Le magnétisme propose un temps de décélération profonde. Il ne prétend pas résoudre les causes du stress, mais il offre un espace pour souffler.",
      "En complément d'un suivi médical si nécessaire, il peut contribuer à un mieux-être global, selon les personnes.",
    ],
  },
];
